### PR TITLE
Fix query order by random

### PR DESCRIPTION
**Pull request by xemle**
Hi @vityav 

I am surprised by no performance impact. That is great. Thank you for testing it.

Here is my refactoring of the `srandom` order. I have refactored the `orderRules` to support direct modifications on the entries.

Is this fine for you?

### CODE REVIEW

**Comment by vityav** [comment]
Looks great to me, and a much nicer solution than the way I hacked it in

**Comment by xemle** [comment]
Thank you for your approval. I will merge this functionality at the weekend. The life is currently busy.

Thank you for your work and this great fix. What comes next?

**Comment by vityav** [comment]
Glad to hear it worked well for you! Life is busy here too, but since you ask: something else I think would be interesting to have as a feature is the ability to search similarity based on tags (possibly weighted by time, or weighted by the existing similarity metric, and possibly including objects detected). You could use something like [MinHash](https://en.wikipedia.org/wiki/MinHash) to precompute the hashes like you're doing for the existing visual fingerprint metric and this would give you the ability to easily browse things that are themed similarly but don't necessarily look similar.  For a bonus challenge it would be fun to account for an extra level in tag similarity. So for example: pictures tagged with "river" and pictures tagged with "lake" might show up as similar despite no pictures tagged with both, if both show up together with other tags like "boat" and "duck".  When I get some time after the holidays I'll start looking into it.

**Comment by xemle** [comment]
Interesting idea.

> feature is the ability to search similarity based on tags

What problem do you try to solve with this feature? What is your workflow where this feature fits in?

> So for example: pictures tagged with "river" and pictures tagged with "lake" might show up as similar despite no pictures tagged with both

How are the tags "river" and "lake" linked together? Can they build, created or linked automatically?

**Comment by vityav** [comment]
In my mind it would serve the same purpose as the existing similarity search, just in tag space instead of visual space. Which is to say, it's not a problem to solve as much as another way to explore the gallery.

The tag connections themselves would be automatically determined via some sort of clustering/similarity algorithm in the more advanced version, but wouldn't even be necessary for the basic version.

**Pull request merged**
